import Link from 'next/link';

export const metadata = {
  title: 'About Philomena’s Digital Connect',
  description: 'Learn how Philomena’s Digital Connect helps school communities reconnect, gather, and belong.'
};

export default function AboutPage() {
  return <main className="public-home public-about-page"><nav className="public-nav" aria-label="Public navigation"><Link className="public-brand" href="/"><span className="public-brand-mark"><img src="/school-logo.png" alt="" /></span><span><strong>Alumni</strong><small>Meet</small></span></Link><div className="public-nav-links open"><Link href="/">Home</Link><Link href="/about" aria-current="page">About</Link><Link href="/#services">Services</Link><Link href="/#pricing">Pricing</Link><Link href="/#contact">Contact</Link></div><div className="public-nav-actions"><Link className="public-login" href="/login">Log in</Link><Link className="public-join" href="/register">Join the community <span aria-hidden="true">↗</span></Link></div></nav><section className="public-about-hero"><p className="public-overline">Our reason for being</p><h1>Keep the good people <em>close.</em></h1><p>Philomena’s Digital Connect is a shared home for the people and places that shaped us. We help schools turn occasional reunions into a living, lasting community.</p><Link className="public-primary-button" href="/register">Join the community <span aria-hidden="true">↗</span></Link></section><section className="public-about-grid"><article><span>01</span><h2>Built around people</h2><p>Every profile, event, and message starts with the same idea: the best part of an institution is the people who carry its story forward.</p></article><article><span>02</span><h2>Made for every chapter</h2><p>Students, recent graduates, and lifelong alumni can find their place here, with a simple experience that grows as their community does.</p></article><article><span>03</span><h2>Led with care</h2><p>Community leaders get the tools to organize events, welcome members, and understand what helps their chapter stay connected.</p></article></section><footer className="public-footer"><div><Link className="public-brand" href="/"><span className="public-brand-mark"><img src="/school-logo.png" alt="" /></span><span><strong>Alumni</strong><small>Meet</small></span></Link><p>Keep the good people close.</p></div><div className="public-footer-end"><span>© 2026 Philomena’s Digital Connect</span><Link href="/">Back home ↑</Link></div></footer></main>;
}
